const prodotti = [

  // LATTICINI
  {nome:"Latte Parmalat Intero ml 1000", prezzo:"€1,60", categoria:"Latticini"},
  {nome:"Latte Parmalat Scremato ml 1000", prezzo:"€1,40", categoria:"Latticini"},
  {nome:"Latte Zymil Verde ml 500", prezzo:"€1,55", categoria:"Latticini"},
  {nome:"Latte Zymil Arancione ml 500", prezzo:"€1,55", categoria:"Latticini"},
  {nome:"Latte Granarolo Scremato ml 1000", prezzo:"€1,40", categoria:"Latticini"},
  {nome:"Latte Arborea ml 1000", prezzo:"€1,30", categoria:"Latticini"},
  {nome:"Mozzarella Lioi", prezzo:"€2,50", categoria:"Latticini"},
  {nome:"Mozzarella Caggiano", prezzo:"€3,10", categoria:"Latticini"},
  {nome:"Mozzarella Scavone", prezzo:"€2,50", categoria:"Latticini"},
  {nome:"Sottilette Classiche", prezzo:"€2,30", categoria:"Latticini"},
  {nome:"Kraft Fettine Classiche", prezzo:"€2,20", categoria:"Latticini"},
  {nome:"Galbani Galbanino Fette", prezzo:"€2,20", categoria:"Latticini"},
  {nome:"Mio Formaggini", prezzo:"€2,00", categoria:"Latticini"},
  {nome:"Parmareggio Cremosini", prezzo:"€1,95", categoria:"Latticini"},
  {nome:"Philadelphia Original", prezzo:"€2,40", categoria:"Latticini"},
  {nome:"Philadelphia Light", prezzo:"€3,40", categoria:"Latticini"},
  {nome:"Philadelphia Senza Lattosio", prezzo:"€2,95", categoria:"Latticini"},
  {nome:"Galbani Nuvola", prezzo:"€2,40", categoria:"Latticini"},
  {nome:"Prealpi Quick", prezzo:"€1,30", categoria:"Latticini"},
  {nome:"Alpina Latticino Fresco Light", prezzo:"€1,40", categoria:"Latticini"},
  {nome:"Asiago DOP", prezzo:"€3,90", categoria:"Latticini"},
  {nome:"Gorgonzola Dolcetto", prezzo:"€2,80", categoria:"Latticini"},
  {nome:"Gorgonzola Classic", prezzo:"€1,85", categoria:"Latticini"},
  {nome:"Grana Padano Fette", prezzo:"€2,40", categoria:"Latticini"},
  {nome:"Stracchino Nonno Nanni", prezzo:"€2,00", categoria:"Latticini"},
  {nome:"Robiola Nonno Nanni", prezzo:"€1,90", categoria:"Latticini"},
  {nome:"Yogurt Activia", prezzo:"€3,50", categoria:"Latticini"},
  {nome:"Yogurt Intero Bianco", prezzo:"€1,20", categoria:"Latticini"},
  {nome:"Actimel", prezzo:"€4,30", categoria:"Latticini"},
  {nome:"Milk Benessere", prezzo:"€2,80", categoria:"Latticini"},
  {nome:"Burro Galbani Santa Lucia gr.250", prezzo:"€3,95", categoria:"Latticini"},
  {nome:"Burro Fattorie Lucane gr.125", prezzo:"€1,60", categoria:"Latticini"},

  // SALUMI (prezzo al 100g)
  {nome:"Prosciutto Cotto", prezzo:"€1,80 / 100g", categoria:"Salumi"},
  {nome:"Prosciutto Crudo", prezzo:"€3,50 / 100g", categoria:"Salumi"},
  {nome:"Speck", prezzo:"€2,90 / 100g", categoria:"Salumi"},
  {nome:"Salame Napoli", prezzo:"€2,50 / 100g", categoria:"Salumi"},
  {nome:"Salame Ungherese", prezzo:"€2,50 / 100g", categoria:"Salumi"},
  {nome:"Salame Piccante", prezzo:"€2,50 / 100g", categoria:"Salumi"},
  {nome:"Mortadella", prezzo:"€1,70 / 100g", categoria:"Salumi"},
  {nome:"Prosciutella", prezzo:"€1,80 / 100g", categoria:"Salumi"},
  {nome:"Pancetta Coppata", prezzo:"€2,50 / 100g", categoria:"Salumi"},

  // PASTA E DISPENSA
  {nome:"Pasta Divella", prezzo:"€0,80", categoria:"Pasta"},
  {nome:"Pasta De Cecco", prezzo:"€1,30", categoria:"Pasta"},
  {nome:"Pasta Rummo", prezzo:"€1,10", categoria:"Pasta"},
  {nome:"Riso Gallo Chicchi di Riso", prezzo:"€2,30", categoria:"Pasta"},
  {nome:"Riso Gallo Blond Insalate", prezzo:"€2,90", categoria:"Pasta"},
  {nome:"Riso Gallo Blond Integrale", prezzo:"€3,40", categoria:"Pasta"},
  {nome:"Riso Divella Carnaroli", prezzo:"€2,90", categoria:"Pasta"},
  {nome:"Riso Divella Ribe", prezzo:"€2,80", categoria:"Pasta"},
  {nome:"Riso Curtiriso", prezzo:"€2,90", categoria:"Pasta"},

  // CONSERVE
  {nome:"Passata Mutti", prezzo:"€1,60", categoria:"Conserve"},
  {nome:"Polpa Mutti", prezzo:"€1,75", categoria:"Conserve"},
  {nome:"Pomodori Pelati Divella", prezzo:"€0,80", categoria:"Conserve"},
  {nome:"Pomodori con Buccia Divella", prezzo:"€0,85", categoria:"Conserve"},
  {nome:"Uova Agriovo", prezzo:"€2,20", categoria:"Conserve"},
  {nome:"Tonno Rio Mare Olio di Oliva 4x80g", prezzo:"€6,50", categoria:"Conserve"},
  {nome:"Tonno Rio Mare al Naturale", prezzo:"", categoria:"Conserve"},
  {nome:"Tonno Nostromo Goccia d'Olio 3x65g", prezzo:"€2,80", categoria:"Conserve"},
  {nome:"Tonno Mister Ton Olio di Girasole 3x80g", prezzo:"€2,30", categoria:"Conserve"},
  {nome:"Filetti di Tonno Callipo gr.170", prezzo:"€5,80", categoria:"Conserve"},
  {nome:"Filetti di Sgombro Rio Mare al Naturale", prezzo:"€2,65", categoria:"Conserve"},
  {nome:"Filetti di Acciughe Monte Mare gr.80", prezzo:"€1,90", categoria:"Conserve"},
  {nome:"Filetti di Acciughe Monte Mare gr.160", prezzo:"€3,70", categoria:"Conserve"},
  {nome:"Insalatissime Rio Mare", prezzo:"€2,80", categoria:"Conserve"},
  {nome:"Simmenthal 3x70g", prezzo:"€3,95", categoria:"Conserve"},
  {nome:"Simmenthal 3x90g", prezzo:"€4,90", categoria:"Conserve"},
  {nome:"Maionese Heinz", prezzo:"€2,40", categoria:"Conserve"},
  {nome:"Maionese Calvé", prezzo:"€2,20", categoria:"Conserve"},
  {nome:"Ketchup Calvé", prezzo:"€2,20", categoria:"Conserve"},
  {nome:"Ketchup Heinz", prezzo:"€2,40", categoria:"Conserve"},
  {nome:"Pesto Genovese Barilla", prezzo:"€2,60", categoria:"Conserve"},
  {nome:"Peperoni in Aceto Ponti", prezzo:"€2,80", categoria:"Conserve"},
  {nome:"Olive Saclà", prezzo:"€2,10", categoria:"Conserve"},
  {nome:"Funghi Champignons Di Carlo", prezzo:"€1,30", categoria:"Conserve"},
  {nome:"Mais Valfrutta", prezzo:"€1,00", categoria:"Conserve"},
  {nome:"Fagioli Cannellini Valfrutta", prezzo:"€1,20", categoria:"Conserve"},
  {nome:"Fagioli Borlotti Valfrutta", prezzo:"€1,20", categoria:"Conserve"},
  {nome:"Piselli Valfrutta", prezzo:"€1,40", categoria:"Conserve"},
  {nome:"Vino Bianco Tavernello", prezzo:"€2,15", categoria:"Conserve"},
  {nome:"Vino Rosso Tavernello", prezzo:"€2,15", categoria:"Conserve"},
  {nome:"Aceto di Vino Ponti", prezzo:"€1,50", categoria:"Conserve"},
  {nome:"Aceto di Alcol Casaceto", prezzo:"€1,00", categoria:"Conserve"},

  // COLAZIONE
  {nome:"Biscotti Mulino Bianco", prezzo:"€2,20", categoria:"Colazione"},
  {nome:"Biscotti Mulino Bianco Farciti", prezzo:"€3,40", categoria:"Colazione"},
  {nome:"Biscotti Divella", prezzo:"€1,50", categoria:"Colazione"},
  {nome:"Pan di Stelle", prezzo:"€2,80", categoria:"Colazione"},
  {nome:"Gocciole Pavesi", prezzo:"€3,30", categoria:"Colazione"},
  {nome:"Biscotti Galbusera Senza Zuccheri", prezzo:"€3,20", categoria:"Colazione"},
  {nome:"Biscotti Gran Turchese", prezzo:"€2,45", categoria:"Colazione"},
  {nome:"Biscotti Oro Saiwa", prezzo:"€1,60", categoria:"Colazione"},
  {nome:"Kinder Brioss", prezzo:"€3,50", categoria:"Colazione"},
  {nome:"Kinder Colazione Più", prezzo:"€3,45", categoria:"Colazione"},
  {nome:"Kinder Panecioc", prezzo:"€3,60", categoria:"Colazione"},
  {nome:"Nastrine Mulino Bianco", prezzo:"€2,95", categoria:"Colazione"},
  {nome:"Plum Cake Mulino Bianco", prezzo:"€2,80", categoria:"Colazione"},
  {nome:"Croissant Bauli Albicocca", prezzo:"€2,70", categoria:"Colazione"},
  {nome:"Croissant Bauli Ciliegia", prezzo:"€2,70", categoria:"Colazione"},
  {nome:"Croissant Bauli Crema", prezzo:"€2,70", categoria:"Colazione"},
  {nome:"Croissant Divella", prezzo:"€1,60", categoria:"Colazione"},
  {nome:"Balconi", prezzo:"€1,80", categoria:"Colazione"},
  {nome:"Marmellata Santa Rosa", prezzo:"€2,40", categoria:"Colazione"},
  {nome:"Marmellata Hero Light", prezzo:"€2,85", categoria:"Colazione"},
  {nome:"Miele Ambrosoli", prezzo:"€3,85", categoria:"Colazione"},
  {nome:"Nutella gr.220", prezzo:"€3,90", categoria:"Colazione"},
  {nome:"Nutella gr.750", prezzo:"€6,80", categoria:"Colazione"},
  {nome:"Caffè Lavazza Rossa 2x250g", prezzo:"€11,90", categoria:"Colazione"},
  {nome:"Caffè Kimbo 250g", prezzo:"€5,80", categoria:"Colazione"},
  {nome:"Tè StarTea Classico", prezzo:"€1,80", categoria:"Colazione"},
  {nome:"Tè StarTea Verde", prezzo:"€2,40", categoria:"Colazione"},
  {nome:"Tè StarTea Limone", prezzo:"€2,30", categoria:"Colazione"},
  {nome:"Tisane L'Angelica", prezzo:"€2,90", categoria:"Colazione"},

  // BIBITE
  {nome:"Acqua Levissima", prezzo:"€3,30", categoria:"Acqua"},
  {nome:"Acqua Lilia", prezzo:"€2,50", categoria:"Acqua"},
  {nome:"Acqua Sorgesana", prezzo:"€2,50", categoria:"Acqua"},
  {nome:"Acqua Rocchetta", prezzo:"€4,00", categoria:"Acqua"},
  {nome:"Acqua Sveva", prezzo:"€2,50", categoria:"Acqua"},
  {nome:"Acqua Gaudianello", prezzo:"€2,80", categoria:"Acqua"},
  {nome:"Acqua Lete", prezzo:"€2,90", categoria:"Acqua"},
  {nome:"Acqua Uliveto", prezzo:"€4,00", categoria:"Acqua"},
  {nome:"Coca Cola Lt 1,5", prezzo:"€2,40", categoria:"Bibite"},
  {nome:"Fanta Lt 1,5", prezzo:"€2,00", categoria:"Bibite"},
  {nome:"Estathe Limone Lt 1,5", prezzo:"€2,30", categoria:"Bibite"},
  {nome:"Estathe Pesca Lt 1,5", prezzo:"€2,30", categoria:"Bibite"},
  {nome:"Gassosa Lt 1,5", prezzo:"€2,00", categoria:"Bibite"},
  {nome:"Succo Yoga", prezzo:"€1,60", categoria:"Bibite"},
  {nome:"Succo Pfanner", prezzo:"€2,50", categoria:"Bibite"},
  {nome:"Succo Santal", prezzo:"€1,90", categoria:"Bibite"},
  {nome:"Birra Peroni", prezzo:"€1,00", categoria:"Bibite"},
  {nome:"Birra Tuborg", prezzo:"€1,30", categoria:"Bibite"},
  {nome:"Birra Nastro Azzurro", prezzo:"€1,20", categoria:"Bibite"},
  {nome:"Birra Corona", prezzo:"€1,50", categoria:"Bibite"},

  // DETERSIVI
  {nome:"Detersivo Piatti Svelto Limone", prezzo:"€2,40", categoria:"Detersivi"},
  {nome:"Detersivo Piatti Svelto Aceto", prezzo:"€2,40", categoria:"Detersivi"},
  {nome:"Detersivo Piatti Nelsen", prezzo:"€2,00", categoria:"Detersivi"},
  {nome:"Detersivo Piatti Scala", prezzo:"€1,40", categoria:"Detersivi"},
  {nome:"Detersivo Lavatrice Sole", prezzo:"€1,90", categoria:"Detersivi"},
  {nome:"Detersivo Lavatrice Perla", prezzo:"€2,50", categoria:"Detersivi"},
  {nome:"Ammorbidente Soflan", prezzo:"€1,90", categoria:"Detersivi"},
  {nome:"Ammorbidente Spuma di Champagne", prezzo:"€1,90", categoria:"Detersivi"},
  {nome:"Detersivo Pavimenti Amuchina", prezzo:"€2,60", categoria:"Detersivi"},
  {nome:"Detersivo Pavimenti Mastro Lindo", prezzo:"€2,70", categoria:"Detersivi"},
  {nome:"Detersivo Pavimenti Ace", prezzo:"€1,90", categoria:"Detersivi"},
  {nome:"Detersivo Pavimenti Ajax", prezzo:"€2,50", categoria:"Detersivi"},
  {nome:"Detersivo Bagno Smac", prezzo:"€1,90", categoria:"Detersivi"},
  {nome:"Sgrassatore Chanteclair", prezzo:"€2,65", categoria:"Detersivi"},
  {nome:"Sgrassatore Winni's", prezzo:"€2,40", categoria:"Detersivi"},
  {nome:"Sgrassatore Smac", prezzo:"€2,20", categoria:"Detersivi"},
  {nome:"Sgrassatore Quasar", prezzo:"€2,60", categoria:"Detersivi"},
  {nome:"Vetril", prezzo:"€2,40", categoria:"Detersivi"},
  {nome:"Candeggina Ace Classica", prezzo:"€2,50", categoria:"Detersivi"},
  {nome:"Candeggina Fiorillo", prezzo:"€1,80", categoria:"Detersivi"},

  // IGIENE
  {nome:"Shampoo Pantene", prezzo:"€3,60", categoria:"Igiene"},
  {nome:"Shampoo Garnier Fructis", prezzo:"€2,70", categoria:"Igiene"},
  {nome:"Shampoo Sunsilk", prezzo:"€2,30", categoria:"Igiene"},
  {nome:"Balsamo Pantene", prezzo:"€3,60", categoria:"Igiene"},
  {nome:"Bagnoschiuma Dove", prezzo:"€3,50", categoria:"Igiene"},
  {nome:"Bagnoschiuma Vidal", prezzo:"€1,85", categoria:"Igiene"},
  {nome:"Bagnoschiuma Malizia", prezzo:"€2,90", categoria:"Igiene"},
  {nome:"Sapone Intimo Neutro Med", prezzo:"€2,30", categoria:"Igiene"},
  {nome:"Sapone Intimo Chilly", prezzo:"€3,70", categoria:"Igiene"},
  {nome:"Sapone Mani Venus", prezzo:"€1,60", categoria:"Igiene"},
  {nome:"Dentifricio Az", prezzo:"€1,50", categoria:"Igiene"},
  {nome:"Dentifricio Iodosan", prezzo:"€2,40", categoria:"Igiene"},
  {nome:"Spazzolino Mentadent", prezzo:"€1,50", categoria:"Igiene"},
  {nome:"Alcol Aoyd", prezzo:"€2,20", categoria:"Igiene"},
  {nome:"Assorbenti Lines Seta", prezzo:"€2,90", categoria:"Igiene"},

  // CASA
  {nome:"Tovaglioli Corona", prezzo:"€1,40", categoria:"Casa"},
  {nome:"Scottex Daily", prezzo:"€1,50", categoria:"Casa"},

];
